
export const GRID_SIZE = 11;
export const WORDS_PER_GAME = 14;

export const PORTUGUESE_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

export const WORD_LIST = [
  'AMARELO', 'AMIGO', 'ANIMAL', 'ARVORE', 'AZUL', 'BOLA', 'BONECA',
  'BRINCAR', 'CADEIRA', 'CAMINHO', 'CANTAR', 'CARRO', 'CASA', 'CEU',
  'CIDADE', 'COMIDA', 'CORACAO', 'CORRER', 'DEDO', 'ESCOLA', 'ESTRELA',
  'FAMILIA', 'FELIZ', 'FESTA', 'FLOR', 'FOGO', 'FOLHA', 'FRUTA',
  'GATO', 'GIRAFA', 'JANELA', 'JARDIM', 'LARANJA', 'LEAO', 'LIVRO',
  'LUA', 'LUZ', 'MAE', 'MACA', 'MESA', 'MUSICA', 'NATUREZA', 'NOITE',
  'PAI', 'PAPEL', 'PARQUE', 'PEIXE', 'PORTA', 'PRAIA', 'PRESENTE',
  'PROFESSOR', 'RATO', 'RIO', 'ROUPA', 'SAPATO', 'SENTAR', 'SOL',
  'SORRISO', 'TERRA', 'VERDE', 'VERMELHO', 'AGUA'
];
   